import { NextPage } from "next";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import React from "react";
import { ContactForm } from "../components/ContactForm";

const ProducDetailPage: NextPage = ({}) => {
  const router = useRouter();
  const { productName } = router.query as any;

  return (
    <>
      <Head>
        <title> {productName} - Calmato</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProductSwitcher productType={productName} />
      </main>
    </>
  );
};

function switcher(prodoctType: string) {
  switch(prodoctType) {
    case "shs_web": {
      return <ContactForm />;
    }
    case "gran_cook": {
      break;
    }
    case "presto_pay": {
      break;
    }
    case "gran_book": {
      break;
    }
  }
}

interface Props {
  productType: string;
}


export function ProductSwitcher(props: Props) {
  const { productType } = props;
  return <>{switcher(productType)}</>;
}

export default ProducDetailPage;
