import { propNames } from "@chakra-ui/styled-system";
import { GetStaticPropsContext, NextPage, NextPageContext } from "next";
import { useRouter } from "next/dist/client/router";
import Head from "next/head";
import React from "react";

interface Props {
  contents: string;
}

const ProducDetailPage = function ProducDetailPage(props: Props)  {
  const router = useRouter();
  const { productName } = router.query;
  const contents = props.contents;

  return (
    <>
      <Head>
        <title> {productName} - Calmato</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {contents}
      </main>
    </>
  );
};

export async function getStaticProps(context: GetStaticPropsContext) {
  const fileName = `${context.params?.productName}.md`
  const filePath =  `./markdown/${fileName}`;

  return {
    props: {contents: filePath}, // will be passed to the page component as props
  };
}

// This function gets called at build time
export async function getStaticPaths() {
  const products = ["shs_web", "gran_cook", "presto_pay", "gran_book"];

  return {
    paths: products.map((name) => {
      return {
        params: {
          productName: name,
        },
      };
    }),
    fallback: false,
  };
}

export default ProducDetailPage;
