import React, { useCallback, useState } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { TopPageImage } from "../components/TopPageImage";
import { Box, Container, Grid } from "@chakra-ui/layout";
import { Text, Flex, List, ListItem } from "@chakra-ui/react";
import { ContentsSwitcher } from "../components/templates/ContentsSwitcher";
import { CategoryName } from "../types";

const categories: CategoryName[] = ["Product", "Profile", "Contact"];

const Home: NextPage = () => {
  const [selected, setSelected] = useState<number>(0);

  const handleClickCategory = useCallback((idx: number) => {
    setSelected(idx);
  }, []);

  return (
    <>
      <Head>
        <title>Calmato</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopPageImage src="img/image.png" />

        <Container maxW="container.lg">
          <Box p={8}>
            <Text fontSize="4xl">About</Text>

            <Flex>
              <Box flex="1">
                <Text mb={4}>Category: {categories[selected]}</Text>
                <ContentsSwitcher contentType={categories[selected]} />
              </Box>

              <Box flex="0.5" pl={4}>
                <Text mb={4}>Category</Text>
                <List>
                  {categories.map((name, idx) => (
                    <ListItem
                      key={idx}
                      as="button"
                      display="block"
                      mb={4}
                      onClick={() => handleClickCategory(idx)}
                    >
                      <Text
                        fontSize="2xl"
                        {...(idx === selected
                          ? { fontWeight: "bold" }
                          : { color: "gray" })}
                      >
                        {name}
                      </Text>
                    </ListItem>
                  ))}
                </List>
              </Box>
            </Flex>
          </Box>
        </Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
};

export default Home;
