import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { TopPageImage } from "../components/TopPageImage";
import { Box, Container, Grid } from "@chakra-ui/layout";
import { Text, Flex, List, ListItem } from "@chakra-ui/react";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Calmato</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopPageImage src="img/image.png" />

        <Container maxW="container.lg">
          <Box p={8}>
            <Text fontSize="4xl">About</Text>

            <Flex>
              <Box flex="1">
                <Text>Category:</Text>
              </Box>

              <Box flex="0.5" pl={4}>
                <Text>Category</Text>
                <List>
                  <ListItem>Product</ListItem>
                  <ListItem>Profile</ListItem>
                  <ListItem>Contact</ListItem>
                </List>
              </Box>
            </Flex>
          </Box>
        </Container>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </>
  );
};

export default Home;
